"""empty message

Revision ID: 4e184bf8021a
Revises: 
Create Date: 2019-12-13 18:31:19.972376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e184bf8021a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    op.add_column('Gym_Expenses', sa.Column('gender', sa.String(), nullable=True))
    op.drop_column('Member_Subscription', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Member_Subscription', sa.Column('gender', sa.TEXT(), nullable=True))
    op.drop_column('Gym_Expenses', 'gender')
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
